services:
  db: 
    image: ${DB_IMAGE}:${DB_TAG}
    container_name: ${DB_CONT_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:${DB_DATA_PATH}
  
  adminer:
    image: adminer
    container_name: ${ADMINER_CONT_NAME}
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  data:
    name: ${DB_DATA_VOLUME}
