# Stage 1: build frontend
FROM node:lts-alpine3.21 AS build

WORKDIR /app

COPY package*.json .
RUN npm ci
COPY . .

RUN npm run build

# Stage 2: serve frontend
FROM nginx:stable-alpine

COPY --from=build /app/build/ /usr/share/nginx/html
COPY --from=nginx default.conf /etc/nginx/conf.d/default.conf
